project:
  type: website
  output-dir: docs

website:
  title: "BANA 7042"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/syllabus.qmd
        text: Syllabus
      - text: Slides
        menu:
          - href: slides/index.qmd
            text: "All Slides"
          - href: slides/01-linear-regression.qmd
            text: "01: Linear Regression"
          - href: slides/02-logistic-regression-1.qmd
            text: "02: Logistic Regression I"
          - href: slides/03-logistic-regression-2.qmd
            text: "03: Logistic Regression II"
          - href: slides/04-logistic-regression-3.qmd
            text: "04: Logistic Regression III"
          - href: slides/05-multinomial-ordinal-regression.qmd
            text: "05: Multinomial/Ordinal"
          - href: slides/06-count-regression.qmd
            text: "06: Count Regression"
      - text: Assignments
        menu:
          - href: assignments/index.qmd
            text: "All Assignments"
          - href: assignments/assignment-01.qmd
            text: "Assignment 01"
          - href: assignments/assignment-02.qmd
            text: "Assignment 02"
          - href: assignments/assignment-03.qmd
            text: "Assignment 03"
          - href: assignments/assignment-04.qmd
            text: "Assignment 04"
          - href: assignments/assignment-05.qmd
            text: "Assignment 05"
          - href: assignments/assignment-06.qmd
            text: "Assignment 06"
      - href: assignments/final-exam.qmd
        text: Final Exam
    right:
      - icon: github
        href: https://github.com/bgreenwell/uc-bana7042
        aria-label: GitHub

  sidebar:
    - id: slides
      title: "Lecture Slides"
      contents:
        - slides/index.qmd
        - slides/01-linear-regression.qmd
        - slides/02-logistic-regression-1.qmd
        - slides/03-logistic-regression-2.qmd
        - slides/04-logistic-regression-3.qmd
        - slides/05-multinomial-ordinal-regression.qmd
        - slides/06-count-regression.qmd
    - id: assignments
      title: "Assignments"
      contents:
        - assignments/index.qmd
        - assignments/assignment-01.qmd
        - assignments/assignment-02.qmd
        - assignments/assignment-03.qmd
        - assignments/assignment-04.qmd
        - assignments/assignment-05.qmd
        - assignments/assignment-06.qmd
        - assignments/final-exam.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
