project:
  type: website
  output-dir: _site

website:
  title: "BANA 7042"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/syllabus.qmd
        text: Syllabus
      - href: slides/index.qmd
        text: Slides
      - href: assignments/index.qmd
        text: Assignments

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
